### ISSUE TITLE
Add middleware

### ISSUE THREAD

**Issue by arturictus** [arturictus/hash_map#16]
We should add middlewares:
- before_map
- after_map
- each_property
  - before
  - after

I found this code:
```ruby
  def self.map(hash)
    HashWithIndifferentAccess[
      super(hash).map { |k,v|
        [k, v == '' ? nil : v ]
      }
    ]
  end
```

We should be able to do it by Mapper and for global in a initializer config.
The per class config should override the global config.

**Comment by arturictus** [comment]
@alexcastano

**Comment by GustavoCaso** [comment]
I started working on a solution for this Issue, There is `WIP branch` in my repository https://github.com/GustavoCaso/hash_map/tree/add_middleware.

We can discuss how to add this functionality @arturictus

**Comment by GustavoCaso** [comment]
@arturictus I really not see the utility of an `before_map` middleware could you provided an example ?
